name: Build and Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy build to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22007
          source: "dist/**"
          target: "/var/www/tp_svg/server"
          rm: true
          overwrite: true

      - name: Deploy project config files (package.json, lockfile, etc.)
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22007
          source: |
            package.json
            package-lock.json
            astro.config.mjs
          target: "/var/www/tp_svg/"
          overwrite: true

      - name: Install production dependencies and restart app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22007
          script: |
            cd /var/www/tp_svg
            npm ci --omit=dev
            npm install kleur send server-destroy
            PORT=8088 pm2 delete tp_svg || true
            PORT=8088 pm2 start server/entry.mjs --name tp_svg
